sysdeps: include missing header
If we are going to use `vdpau_error_message` then we must include the
header that defines it, otherwise we get this Gentoo ebuild QA warning:

  QA Notice: Package triggers severe warnings which indicate that it
             may exhibit random runtime failures.
  /var/tmp/portage/x11-libs/libva-vdpau-driver-9999/work/libva-vdpau-driver-9999/src/sysdeps.h:52:13: warning: implicit declaration of function 'vdpau_error_message' [-Wimplicit-function-declaration]